apiRules:
- exclude:
      uidRegex: ^System\.Object
      type: Type
- exclude:
      uidRegex: ^System\.Web\.UI\.Control
      type: Type
- exclude:
      uidRegex: ^CPointSoftware\.ECommerce\.Tools\.MouseOverHyperlink
      type: Type
- exclude:
      uidRegex: ^System\.ComponentModel\.IComponent
      type: Type
- exclude:
      uidRegex: ^System\.Web\.UI\.WebControls
      type: Namespace
- exclude:
      uidRegex: ^System\.Web\.UI
      type: Namespace
- exclude:
      uidRegex: ^.*\.BindTo
      type: Method
- exclude:
      uidRegex: ^.*\.Render
      type: Method
- exclude:
      uidRegex: ^.*\.RenderChildren
      type: Method
- exclude:
      uidRegex: ^.*\.InitializeCell
      type: Method
- exclude:
      uidRegex: ^.*\.CreateField
      type: Method
- exclude:
      uidRegex: ^.*\.CompareTo
      type: Method
- exclude:
      uidRegex: ^.*\.CompareTo
      type: Method
- exclude:
      uidRegex: ^.*\.DataBind
      type: Method
- exclude:
      uidRegex: ^.*\.OnLoad
      type: Method
- exclude:
      uidRegex: ^.*\.OnInit
      type: Method
- exclude:
      uidRegex: ^.*\.DataBind
      type: Method
- exclude:
      uidRegex: ^.*\.OnPreRender
      type: Method
- exclude:
      uidRegex: ^.*\.OnDataBinding
      type: Method      